CREATE DATABASE magus_combathelp_damages CHARACTER SET utf8 COLLATE utf8_hungarian_ci;


CREATE TABLE type_damages(
	weapon_type varchar (20) PRIMARY KEY,
	damages_group varchar(20)
);


INSERT INTO type_damages (weapon_type, damages_group) VALUES 
("Szúrófegyverek", "pierce_damages_group"),
("Zúzófegyverek", "bruise_damages_group"),
("Vágófegyverek", "shear_damages_group");



CREATE TABLE pierce_damages_group(
	tableName varchar(20) PRIMARY KEY,
	area_group varchar(20),
	sp_damage_mild varchar(20),
	sp_damage_serious varchar(20),
	sp_damage_dangerous varchar(20),
	sp_damage_lethal varchar(20),
	commenting varchar(100)
);

INSERT INTO pierce_damages_group (tableName, area_group, sp_damage_mild, sp_damage_serious, sp_damage_dangerous, sp_damage_lethal, commenting) VALUES
("pierce_head", "Fej", "1-2 Ép", "3-4 Ép", "5-6 Ép", "7+ Ép", null),
("pierce_front", "Törzs előlről", "1-3 Ép", "3-6 Ép", "7-10 Ép", "10+ Ép", "lásd még beslőségek sérülésekor Szívbénulás, Tüdősorvadás, Bélsorvadás BM varázslatok"),
("pierce_back", "Törzs hátulról", "1-3 Ép", "3-6 Ép", "7-10 Ép", "10+ Ép", "lásd még beslőségek sérülésekor Szívbénulás, Tüdősorvadás, Bélsorvadás BM varázslatok"),
("pierce_arm", "Kar", "1-2 Ép", "3-4 Ép", "5-6 Ép", null, "Max 6 Ép sebzése lehet"),
("pierce_leg", "Láb", "1-2 Ép", "3-4 Ép", "5-6 Ép", null, "Max 8 Ép sebzése lehet");

CREATE TABLE pierce_head (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	damage_lethal varchar(200),
	affect_lethal varchar (200),
	commenting varchar(100)
);

INSERT INTO pierce_head (id, dice, area, 
				damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, damage_lethal, affect_lethal, commenting) VALUES 
(1,"0-1", "Koponya", 
			"A penge mély nyomot szánt a fejbőrbe, de nem szakítja át a komonyát.","+k6 FP",
			"A szúrás megrepeszti a koponyacsontot, de nem ejt hosszú sebet.","Zavaró hátrány, mérsékelt fájdalom.",
			"Az elemi erejú szúrás áttöri a koponyát, de nem éri el az agyat.","Jelentős hátrány. Heves fájdalom.",
			"A penge áttöri a koponyacsontot és megsérti a lágy részeket.","Jelentős hátrány. Heves fájdalom.",
			null),
(2,	"2-3", "Homlok",	
			"A szúrás megcsúszik a homlokcsonton, hosszú és méy sebet vág a fejbőrbe.","+k6 FP",
			"A penge hegye megrepeszti a homlokcsontot, de nem hatol mélyebbre.","Zavaró hátrány. Gyenge fájdalom.",
			"A penge hegye átszakítja a homlokcsontot, de ezzel el is veszíti erejét.","Zavaró hátrány. Mérsékelt fájdalom.",
			"A penge áthatol a homlokcsonton, és végzetessé váló sérülést okoz a lágyabb részekben.","Jelentős fájdalom. Heves fájdalom.",
			null),		
(3, "4" ,"Halánték", "A homlokcsonton megcsúszió szúrás a halántékhoz veszélyes közelségben ejt mély sebet.","+k6 FP",
			"A halántékot végigmetsző szúrás egészen a fülig mélyen felszántja a fejbőrt és a koponyacsontot.","Gyenge vérzés. Zavaró hátrány. Gyenge fájdalom.",
			"A szúrás közvetlenül a halántékot éri és megrepeszti a csontot.","Gyenge vérzés. Zavaró hátrány. Mérsékelt fájdalom.",
			"A penge átszakítja a vékony halántékcsontot és eléri a sérülékeny, lágyabb rétegeket.","Gyenge vérzés. Jelentős hátrány. Heves fájdalom.",
			null),
(4, "5-6","Arc",
			"A szúrás elkerüli az érzékeny pontokat, megcsúszik az arccsonton, és csúf sebet ejt.","+k6 FP",
			"A fegyver hegye utat talál a csontok között és az arcot átszakítva az arcüregbe, szájba hatol.","Gyenge fájdalom. Zavaró hátrány. Gyenge vérzés.",
			"Hosszú vágás az arcon, mely megrepeszti az arc vagy orrcsontot, éppen elkerüli a szemet.","Mérsékelt fájdalom. Zavaró hátrány. Gyenge vérzés.",
			"A szúrás a szemüregbe hatol. Nem mindig szúrja ki a szemet, de tartós látáskárosodást okoz.","Heves fájdalom. Jelentős hátrány. Gyenge vérzés.",
			null),
(5, "7-9","Nyak/Tarkó",
			"A penge hegye elkerüli a fontos ereket, a gégét, a csigolyákat, de felmetszi a nyakat.","+k6 FP",
			"A nyakat mélyen felsértő szúrás, óhatatlanul felszakít néhányat a kisebb erek közül.","Mérsékelt vérzés. Zavaró hátrány.",
			"A penge átdöfi a nyakat, megsérti a gégét vagy a csigolyákat, de elkerüli a verőeret.","Mérsékelt vérzés. Jelentős hátrány.",
			"A végzetes szúrás felszakítja a nyaki verőeret, íly módon könnyen halálossá válhat.","Heves vérzés. Teljes bénulás.",
			null);

CREATE TABLE pierce_front (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	damage_lethal varchar(200),
	affect_lethal varchar (200),
	commenting varchar(100)
);
			
INSERT INTO pierce_front (id, dice, area, 
				damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, damage_lethal, affect_lethal,commenting) VALUES 	
(1,"0","Jobb kulcscsont",
				"A szúrás felfelé elkerüli a kulcscsontot, érezhető reccsenéssel hatol az izmok közé.","+k6 FP",
				"A szúrás a kulcscsont felett teljesen átüti a csukjásizmot.","Mérsékelt vérzés.",
				"A szúrás megrepeszti a kulcscsontot és fontos inakat, izmokat roncsol.","Mérsékelt vérzés. A jobb kulcscsont részleges bénulása. Gyenge fájdalom.",
				"A szúrás eltöri a kulcscsontot és átszakítja a nyaki verőeret.","Heves vérzés. A jobb kulcscsont teljes bénulása. Mérsékelt fájdalom.",
				null),
(2,"1","Bal kulcscsont", 
				"A szúrás felfelé elkerüli a kulcscsontot, érezhető reccsenéssel hatol az izmok közé.","+k6 FP",
				"A szúrás a kulcscsont felett teljesen átüti a csukjásizmot.","Mérsékelt vérzés.",
				"A szúrás megrepeszti a kulcscsontot és fontos inakat, izmokat roncsol.","Mérsékelt vérzés. A bal kulcscsont részleges bénulása. Gyenge fájdalom.",
				"A szúrás eltöri a kulcscsontot és átszakítja a nyaki verőeret.","Heves vérzés. A bal kulcscsont teljes bénulása. Mérsékelt fájdalom.",
				null),
(3,"2", "Szegycsont",
				"A szúrás megzúzza a szegycsontot. Kellemetlen, de nem túl mély sebet ejt.","+k6 FP",
				"A megreőpedő szegycsont mintha mellvért lenne, megakasztja a szúrást.","Zavaró hátrány. Gyenge fájdalom. +k10 FP",
				"A szúrás ereje eltöri a szegycsontot, a penge hegye eléri a belső szerveket.","Gyenge (belső) vérzés. Jelentős hátrány. Gyenge fájdalom.",
				"A szúrás ettöri a szegycsontot és létfontosságú belső szerveket döf át.","Heves (belső) vérzés. Végzetes hátrány. Mérségkelt fájdalom.",
				null),
(4,"3","Bal mellkas",
				"A szívnek irányzott szúrás elcsúszik a bordákon. Csak felületi sebet ejt, de két bordát megzúz és felsért.","+k6 FP",
				"A penge nem éri el még a szívbúrkot, de megrepeszt két bordát.","Zavaró hátrány. Gyenge fájdalom.",
				"A szúrás áthatol a szétfeszített bordák között és felsérti a szívbúrkot. Könnyen végzetes lehet.","Gyenge (belső) vérzés. Zavaró hátrány. Gyenge fájdalom.",
				"A szúrás utat talál a bordák között és eléri a szivet. Túlélhető, de mindenképpen veszedelmes seb.","Heves (belső) vérzés. Végzetes hátrány. Mérsékelt fájdalom.",
				null),
(5,"4","Jobb mellkas",
				"A lecsúszó penge megzúz két bordát és mély vágást ejt az oldalon.","+k6 FP",
				"A szúrás elakad a bordák között és két bordát megrepeszt.","Zavaró hátrány. Gyenge fájdalom.",
				"A szúrás átcsúszik a bordák között és a tüdőbe szalad.","Gyenge (belső) vérzés. Zavaró hátrány. Gyenge fájdalom*.",
				"A fegyver hegye áthatol két borda között és a tüdőben állapodik meg.","Mérsékelt (belső) vérzés. Jelentős hátrány. Mérsékelt fájdalom.",
				null),
(6,"5-6","Gyomorszáj",
				"Az erőtlen szúrás nem hatol át az izmokon, de fájdalmas sebet ejt.","+k10 Fp",
				"A szúrás széthasítja a hasizmokat, de nem éri a belső szerveket.","Gyenge vérzés. Zavaró hátrány. +k10 FP",
				"A penge áthatol a hasizmon és veszélyes sebet ejt a belső szervekben.","Gyenge (belső) vérzés. Zavaró hátrány.",
				"A halált ígérő szúrás végzetes roncsolást okoz a belső szervekben.","Heves (belső) vérzés. Jelentős hátrány.",
				null),
(7,"7", "Has jobboldalt",
				"Az erőtlen szúrás könnyedén a lágy hasba szalad, de nem hatol mélyre.","+k6 Fp",
				"A penge mély, fájdalmas sebet ejt a hason, de elkerüli a belső szerveket.","Gyenge vérzés. +k6 FP",
				"A penge átdöfi a hadfalat és súlyos sebet ejt a belső szerveken.","+k6 Fp Gyenge (belső) vérzés. Gyenge fájdalom.*",
				"A szúrás átszakítja a hasi izmokat és létfontosságú szerveket döf át.","Mérsékelt (belső) vérzés. Zavaró hátrány*. Mérsékelt fájdalom.",
				null),
(8,"8","Has baloldalt",
				"Az erőtlen szúrás könnyedén a lágy hasba szalad, a legalsó borda alatt.","+k6 Fp",
				"A penge mély. fájdalmas sebet ejt a hason, de elkerüli a belső szerveket.","Gyenge vérzés. +k6 Fp",
				"A penge átdöfi a hasfalat és súlyos sebet ejt a belső szerveketn.","+k6 Fp Gyenge (belső) vérzés. Gyenge fájdalom*.",
				"A szúrás átszakítja a hasi izmokat és létfontosságú szerveket döf át.","Mérsékelt (belső) vérzés. Zavaró hátrány*. Mérsékelt fájdalom.",
				null),
(9,"9","Ágyék",
				"A szúrás csak felületi sebet ejt az érzékeny testtájon, hasfalat, izmokat sért.","Gyenge vérzés.",
				"A penge átdöfi a hasszéli izmokat, hegye hátul, a derékon bukkan elő, de nem érinti a belső szerveket.","Gyenge vérzés. Zavaró hátrány.",
				"A szúrás áthatol az izmokon és mélyen az ágyékba fúródik, a belső szerveket sérti fel.","Mérsékelt (belső) vérzés. Zavaró hátrány.",
				"A penge hegye mélyen az ágyékba hatol, a belső szervek mellet feltéi az itt futó verőereket is.","Heves (belső) vérzés. Zavaró hátrány*.",
				null);

CREATE TABLE pierce_back (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	damage_lethal varchar(200),
	affect_lethal varchar (200),
	commenting varchar(100)
);
			
INSERT INTO pierce_back (id, dice, area, 
				damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, damage_lethal, affect_lethal, commenting) VALUES 
(1,"0","Jobb lapocka",
				"A szúrás elakad a lapocka csonton. Csonthártya sérül, az izmok zúzódnk.", null,
				"A penge éles fájdalom kísértetében a válltrontt hatol.","Gyenge fájdalom.",
				"A szúrás elakad a lapocka csontban, de megrepeszti azt.","Gyenge eérzsb. Zavaró háttány. Gyenge fájdalom +k10 Fp",
				"A szúrás átszakítja a lapocka csontos és eléri a tüdőt.","Ménékelt (belső) vénrzés. Végzetes hátrány. Heves fájdalom."
				,null),
(2,"1-2","Bal lapocka",
				"A szúrás elakad a lapocka csonton. Csonthánya sérül, az izmok rúzódnak.", null,
				"A penge éles fájdalom kisé- retében a vállizomba hatol.","Gyenge fájdalom.",
				"A szúrás elakad a lapocka csontban, de megrepesni azt.","Gyenge vénás. Zavaró hátrány Gyenge fájdalom. +kl0 Fp",
				"A szúrás átszakítja a lapuc-ka csontot és feltépi a szívhez vezető nagyereket.","Heves (belső) vérzés. Végzetes hátrány. Métsékelt fájdalom.",
				null),
(3,"3","Jobb hát",
				"A szúrás elterül a bordákon és hosszú vágást ejt a háton.","Gyenge vérzés.",
				"A szúrás elakad egy megregrepedő hordárn, de nem éri el a belső szerveket. Gyenge vérzés.","Gyenge fájdalom. Zavaró hátrány. +k6 FP",
				"A szúrás áttör két borda között 6 eléri a tüdőt.","Gyenge (belső) vérzés. Mérsékelt fájdalom.",
				"A penge hegye darabokra zúz egy bordát és a tüdőbe fúródik.","Ménékelt (belső) vésés. Végzetes hátrány. Heves fájdalom.",
				null),
(4,"4","Bal hát",
				"A szúrás eltérül a bordákon és hosszú vágást ejt a háton.","Gyenge vérzés.",
				"A szúrás elakad egy megrepedő bordán, de nem éri el a belső szerveket.","Gyenge vérzés. Gyenge fájdalom. Zavaró hátrány, +k6 FP",
				"A szúrás áttör két horda között és eléri a tüdőt.","Mérsékelt fájdalom Gyenge (belső) vérzés.",
				"A penge hegye szilánkokra zúz egy bordát és a szívbe fúródik. Nem minden esethen halálos seb.","Heves (belső) vérzés. Jelentős hátrány. Heves fajdalom.",
				null),
(5,"5",	"Jobb derék",
				"A szúrás elterül a csipőcsonton és mély vágást ejt a deréktáji izmokon.","Gyenge vérzés.",
				"A penge átszalad a csipőcsont feletti hátizmokon, de nem SéTt fel belső szerveket.","Gyenge vértzés. +k6 FP",
				"A szúrás a csípőcsont felett hatol a törzsbe és átszúrja a vesét.","Mérsékelt fájdalom. Jelentős hátrány.",
				"A penge keresztben szalad a törzsön, átdöfve a vesét és más belső szerveket.","Mérsékelt (belső) verzés. Jelentős hátrány. Heves fájdalom.",
				null),
(6,"6",	"Bal derék",
				"A szúrás eltérül a csípőcsonton és mély vágást ejt a detéktályi izmokon.","Gyenge vérzés.",
				"A penge átszalad a csípőcsont feletti hátizmokon. de nem sért fel belső szerveket.","Gyenge vérzés. +k6 FP",
				"A szúrás a csípőcsont felett hatol a törzsbe és átszúria a vesét.","Mérsékelt fájdalom. Jelentős hátrány.",
				"A penge keresztben átszalad a törzsön, átdöfve a vesét és más belső szerveket.","Mérsékelt (belső) vérzés. Jelentős hátrány. Heves fájdalom.",
				null),
(7,"7","Ülep",
			"Hümm... Általános derültsé, de amúgy semmi komoly.","Állva étkezés.",
			"A szúrás roncsolja a farizmokat, mély sebet ejt.","Gyenge vérzés Haladási selsmség: 50%",
			"A penge mélyen a húsba mar, elérve a medencét és a combot mozgató izmokat.","Gyenge vérzés. Haladási sbesség:30%. Zavaró hátrány.",
			"A szúrás átvág egy mélyen futó artériát, nem kímélve az izmokat sem.","Mérsékelt vérzés. Haladási sebesség: 10%",
			null),
(8,"8-9","Gerinc",
			"A penge koppanva akad fenn az egyik gerinctövisen.","+k6 FP",
			"A szúrás eléri a gerincet körülölelő izmokat, de nem sért létfontosságú szervet.","Mérsékelt vérzés. Gyenge fájdalom. Zavaró hátrány.",
			"A penge megsérti a gerincvelőt, részlegtnen megbénítva mindkét alsó végtagot.","Mérsékelt vérzés. Jelentős hátrány. Mérsékelt fájdalom. k6 órára Részleges bénulás.",
			"A támadás, szétzúzva egy esigolyanyúlványt, átmetszi a verőeret és a gerinevelőt.","Heves vérzés. Teljes bénolás válltól lefelé. Heves fájdalom.",
			null);


			
CREATE TABLE pierce_arm (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	commenting varchar(100)
);
			
INSERT INTO pierce_arm (id, dice, area, 
				damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, commenting) VALUES 
(1,"0-2","Váll",
			"Az elcsúszó szúrás felhasítja a vállat. A vállizom megsérül, de a csont nem.","Gyenge vérzés. Zavaró hátrány.",
			"A penge átdöfi a kart, súlyosan megsértve az izmokat és feljarcolva a csonthártyát.","Teljes kar részleges bénulása. Mérsékelt vérzés. Jelentős hátány a sérült kar használatára.",
			"A penge hegye féltépi a karba futó verőeret és a váll porcai közé fúródik. Heves vérzés.","Mérsékelt fájdalom. A kar Teljes bénulása. Jelentős hátrány.",
			null),
(2,"3","Felkar",
			"A szúrás pontatlan, a penge végighasítja a felkart, de nem fúródik bele.","Gyenge vérzés.",
			"A szúrás lecsúszik a megrepedő karcsontról és mélyen feltépi a felkart.","Gyenge vérzés. Jelentős hátrány.",
			"A penge érzékeny ponton átmerszi az izom és feltép a verőeret.","Heves vérzés. Teljes bénulás a felkartól lefelé. Jelentős hátrány.",
			null),
(3,"4-5", "Könyök",
			"A penge a könyökbe vág, de nem fúródik bele. Az érzékeny porcok enyhén sérülnek.","+k6 Fp. Gyenge vérzés. Zavaró hátrány.",
			"A fegyver hegye a könyökízületbe fúródik, több itt futó eret is felszakít.","Mérsékelt vérzés. Az alkar Részleges bénulása. Gyenge fájdalom.",
			"A szórás valósággal szétroncsolja a könyökporcot és feltépi a karhajlatban futó ereket.","Mérsékelt vérzés. Az alkar Teljes bénulása. Mérsékelt fájdalom.",
			null),
(4,"6-7","Alkar",
			"A szúrás végigszánt az alkaron, hosszú, mély vágásr ejtve.","Gyenge vérzés.",
			"A két alkarcsont között átszaladó penge átdöfi az alkart, súlyosan károsítva az izomrostokat.","Gyenge vérzés. Az alkartól lefelé Részleges bénulás.",
			"A szúrás kereszben, csontig felvágja az alkart, elmetszve az izmokat, inakat és ereket.","Teljes bénulás. Mérsékelt vérzés. Gyenge fájdalom.",
			"Max 4 Ép sebzése lehet"),
(5,"8","Csukló",
			"A szúrás nem ejt mély és végzetes sebet, de roncsolja a sérülékeny csuklóízületet.","A kézre Jelentős hátrány. Gyenge fájdalom.",
			"A fegyver hegye érezhető reccsenéssel fúródik a csuklóízületbe, de elkerüli a verőeret.","Alkar Részleges bénulása. Mérsékelt fájdalom.",
			"A penge belefúródik a csuklóba, feltépi a verőeret és használhatatlanná roncsolja az ízületet.","Alkar Teljes bénulása. Mérsékelt fájdalom. Mérsékelt vérzés.",
			"Max 4 Ép sebzése lehet"),
(6,"9","Kézfej",
			"A szúrás csontig felmetsz kéz ujjat, megsérti az ujjízületeket is.","Zavaró hátrány. Gyenge vérzés.",
			"A penge feltépi a kézhátat és összezúzza a kézcsontokat.","Gyenge vérzés. Gyenfe fájdalom. Alkar Részleges bénulása.",
			"A fegyver átdöfi a kézfejet, hegye a tenyéren bukkan elő. A kéztőcsontok összetörnek.","Alkar Teljes bénulása. Gyenge vérzés. Mérsékelt fájdalom.",
			"Max 4 Ép sebzése lehet");

			
CREATE TABLE pierce_leg (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	commenting varchar(100)
);
			
INSERT INTO pierce_leg (id, dice, area, 
				damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, commenting) VALUES 
(1,"0-4","Comb",
			"A szórás mély vágást metsz a combizomba, de elkerüli a főbb ereket.","Gyenge vérzés.",
			"A penge átdöfi a combot, kellemetlen, a mozgást zavaró, de nem végzetes sebet ejtve.","Haladási sebesség: 70%. Gyenge vérzés. Zavaró hátrány.",
			"A szórás csak a megrepedő combcsontban akad el, mély, tavaró sebet ejtve a lábon.","Részleges bénulás. Mérsékelt vérzés. Zavaró hátrány. Haladási sebesség: 50%",
			null),
(2,"5","Térd",
			"A pontatlan szőrás inkább náhásnak minősül. Megsérit a térdhajlat inait, de nem metszi el azokat.","+k10 Fp. Haladási sebesség: 80%",
			"Hideg acél hatlp a térdet alkotó csontok közé, de csak mérsékelt roncsolást okoz.","Haladási sebesség: 50%. Zavaró hátrány. Gyenge fájdalom.",
			"A szórás mélyen a térdízületbe hatol, nem csak a porcokat roncsolja szét, de átvágja a térdszallagokat is.","Teljes bénulás. Zavaró hátrány. Mérsékelt fájdalom.",
			null),
(3,"6-7","Lábszár",
			"A sípcsonton megcsúszó szúrás felsérti a csonthártyát és a vádli izmait.","+k6 Fp",
			"A szúrás belefúródik a megrepedő csonthártyába.","+k6 Fp. Zavaró hátrány. Haladási sebesség 80%",
			"A szúrás oldalról átdöfi a vádlit, elmetszve az izmokat.","Mérsékelt fájdalom. Gyenge vérzés. Zavaró hátrány. Haladási sebesség 70%",
			null),
(4,"8","Boka",
			"A fegyver hegye belemetsz a bokaízületbe, könnyű, de kellemetlen sebet ejtve.","Gyenge vérzés. Haladási sebesség: 80%",
			"A penge a bokaízületbe szalad, de kifordul a sebből, nem reszi mozgásképtelenné a lábfejet.","Gyenge vérzés. Haladási sebesség: 60%",
			"A szúrás az ízület mögött keresztben átszalad a bokán, látfontosságú inakat vég el.","A lábfej Teljes bénulása. Gyenge vérzés. Jelentős hátrány. Haladási sebesség: 40%",
			null),
(5,"9","Lábfej",
			"A csontokkal teli lábfejen elcsúszik a szúrás, hosszú, kellemetlen vágást ejtve.","Gyenge fájdalom. Haladási sebesség: 90%",
			"A penge elakad a lábfej csontjaiban, de kettőt is megrepeszt és kifordít a helyéről.","Lábfej Részleges bénulása. Gyenge fájdalom. Haladási sebesség: 70%",
			"A fegyver átdöfi a lábfejet, a földhöz szegezi. Csontok törnek, szalagok szakadnak.","Mérsékelt fájdalom. Jelentős hátrány. Gyenge vérzés. Lábfej Részleges bénulása. Haladási sebesség: 50%",
			null);
			
			

CREATE TABLE bruise_damages_group(
	tableName varchar(20) PRIMARY KEY,
	area_group varhcar(20),
	sp_damage_mild varchar(20),
	sp_damage_serious varchar(20),
	sp_damage_dangerous varchar(20),
	sp_damage_lethal varchar(20),
	commenting varchar(100)
);

INSERT INTO bruise_damages_group (tableName, area_group, sp_damage_mild, sp_damage_serious, sp_damage_dangerous, sp_damage_lethal, commenting) VALUES
("bruise_head", "Fej", "1-2 Ép", "3-4 Ép", "5-6 Ép", "7+ Ép", null),
("bruise_front", "Törzs előlről", "1-2 Ép", "3-4 Ép", "5-6 Ép", "7+ Ép", "* lásd még ET Betegségek leírás; tüdősérülés az Állóképességet felezi"),
("bruise_back", "Törzs hátulról", "1-2 Ép", "3-4 Ép", "5-6 Ép", "7+ Ép", null),
("bruise_arm", "Kar", "1-2 Ép", "3-4 Ép", "5-6 Ép", null, "Max 6 Ép sebzése lehet"),
("bruise_leg", "Láb", "1-2 Ép", "3-4 Ép", "5-6 Ép", null, "Max 8 Ép sebzése lehet");
			
			

CREATE TABLE bruise_head (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	damage_lethal varchar(200),
	affect_lethal varchar (200),
	commenting varchar(100)
);

INSERT INTO bruise_head (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, damage_lethal, affect_lethal, commenting) VALUES
(1,"0-2","Agykoponya",
		"A csapás csekély erővel éri el a célt, komolyabb következményekkel nem jár.","Szédülés.",
		"A lecsapó fegyver véres zúzott seet ejt a fejtetőn.","Szédülés. Gyenge fájdalom.", 
		"A támadás megrepeszti a koponyacsontot, tenyérnyi bőrt nyúzva le.","Kábulás. Mérsékelt fájdalom.",
		"A csapás bezúzza a koponyát és... a hatás az ÉP veszteségtől függ.","Ájulás. Mérsékelt vérzés.",
		null),
(2,"3-4", "Homlok",
		"A csapás a homlokcsonton csattan, de nem szakítja be.","Szédülés.",
		"A csapás zúzott sebet ejt a homlokon, de nem szakítja át.","Szédülés. Gyenge fájdalom.",
		"Az erős csapás megrepeszti a homlokcsontot.","Kábulás. Mérsékelt fájdalom.",
		"A csapás beszakítja a homlokcsontot és végzetes agysérülést okoz.","Ájulás. Mérsékelt vérzés.",
		null),
(3,"5","Halánték",
		"A fegyver a halántékhoz veszélyes közelségben csap le.","Szédülés.",
		"A csapás eléri a halántékot és megrepeszti a vékony csontot.","Szédülés. Gyenge fájdalom.",
		"A csapás bezúzza a fejtetőhöz képest, papírvékony halántékot.","Ájulás. Mérsékelt vérzés.",
		"A csapás bezúzza a fejtetőhöz képest papírvékony halántékot.","Ájulás. Mérsékelt vérzés.",
		null),
(4,"6-7","Arckoponya",
		"Gyenge zúzódás az arcon. Véraláfutás, csúf, lila foltok.",null,
		"A csapás bezúzza az orrcsontot.","Gyenge vérzés. Mérsékelt fájdalom.",
		"A fegyver oldalról sújt le, elkerüli a szemet, de megrepeszti a járomcsontot.","Kábulás. Gyenge vérzés.",
		"A zúzás szétroncsolja az arcot. A finom csontok szilánkokra törnek.","Ájulás. Mérsékelt vérzés.",
		null),
(5,"8-9","Nyak/Tarkó",
		"A csapás oldalról éri a nyakat. A megfeszülő izmok elnyeik az erejét.",null,
		"A csapás a gégét éri, de nem zúzza össze, múlandó fulladást okoz."," Gyenge fájdalom légzés közben. Zavaró háztány.",
		"A csapás a tarkót éri, közvetlenül nem okoz életveszélyes sebet.","Kábulás. Mérsékelt fájdalom.",
		"A lesújtó fegyver bezúzza a gégét, fulladást okozva.","Mérsékelt (belső) vérzés. Végtezes hátrány.",
		null);



CREATE TABLE bruise_front (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	damage_lethal varchar(200),
	affect_lethal varchar (200),
	commenting varchar(100)
);
			
INSERT INTO bruise_front (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, damage_lethal, affect_lethal, commenting) VALUES

(1,"0","Jobb kulcscsont",
		"A csapás véraláfutást és zúzódást okoz a kulcscsont táji izmokban.","+k6 Fp.",
		"A lesújtó fegyver megrepeszti a kulcscsontot."," Mérségkelt fájdalom. Részleges bénulás a jobb karon.",
		"A csapás eltröi a kulcscsontot, a szilálkok belső sérülést okoznak.","Gyenge vérzés. Részleges bénulás a jobb karon.",
		"Nyílt törés a kulcscsonton, a csonk feltépi az alatta futó verőeret.","Heves vérzés. Teljes bénulás a jobb karon.", 
		null),
(2,"1","Bal kulcscsont",
		"A csapás véraláfutást és zúzódást okoz a kulcscsont táji izmokban.","+k6 Fp.",
		"A lesújtó fegyver megrepeszti a kulcscsontot.","Mérségkelt fájdalom. Részleges bénulás a bal karon.",
		"A csapás eltröi a kulcscsontot, a szilálkok belső sérülést okoznak.","Gyenge vérzés. Részleges bénulás a bal karon.",
		"Nyílt törés a kulcscsonton, a csonk feltépi az alatta futó verőeret.","Heves vérzés. Teljes bénulás a bal karon.", 
		null),
(3,"2","Szegycsont",
		"A csapás megzúzza a szegycsontot, de az ereje nem elegendő a beszakításához.","+k6 Fp.",
		"A megrepedő szegycsont felfogja az ütést.","Gyenge fájdalom. Zavaró hátrány.",
		"A csapás ereje áttüri a szegycsontot, minden mozdulat nyílalló fájdalommal jár.","Mérsékelt fájdalom. Jelentős hátrány.",
		"A darapokra törő szegycsont szilánkjai belső szervekbe, szívbe, tüdőbe fúródnak.","Mérsékelt (belső) vérzés. Heves fájdalom. Végzetes hátrány.",
		null),
(4,"3","Bal mellkas",
		"A csapás csúf, fájdalmas zúzódást okoz a bordaíven.",null,
		"A megrepedő bordák (miként egy mellvért) felfogják az ütést.","Gyenge fájdalom. Zavaró hátrány.",
		"A csapás három bordát is eltör, minden mozgás fájdalmat okoz.","Gyenge vérzés. Mérsékelt fájdalom. Jelentős hátrány.",
		"A bezúzott bordák csonkjai felszaggatják a szívbe futó ereket.","Mérdékelt (belső) vérzés. Heves fájdalom. Végzetes hátrány.",
		null),
(5,"4","Jobb mellkas",
		"A csapás csúf, fájdalmas zúzódást okoz a bordaíven.",null,
		"A megrepedő bordák (miként egy mellvért) felfogják az ütést.","Gyenge fájdalom. Zavaró hátrány.",
		"A csapás három bordát is eltör, minden mozgás fájdalmat okoz.","Gyenge vérzés. Mérsékelt fájdalom. Jelentős hátrány.",
		"A bezúzott bordák csonkjai a tüdőbe fúródnak.","Mérdékelt (belső) vérzés. Heves fájdalom. Végzetes hátrány.",
		null),
(6,"5-6","Gyomorszály",
		"Fájdalmas csapás érti a gyomorszájat.","+k6 Fp.",
		"Kirobbanó, gyorsan múló fájdalom a gyomorszájban.","2 körig tartó Kábulsat. +k10 Fp.",
		"Gyorsan múló fájdalom a gyomorszályban, belső sérülések.","+k10 Fp, 4 körig Kábulat. Gyenge belső vérzés.",
		"A csapás végzetes belső sérülést okoz.","4 körig Kábulat*. Mérsékelt (belső) vérzés. Mérsékelt fájdalom.",
		null),
(7,"7","Has jobboldalt",
		"A csapás kellemetlen hastájéli zúzódással jár, de komoly sérülész nem okoz.","+k6 Fp.",
		"Fájdalmas, a mozgást nehezítő zúzódás a törzs izmaiban.","+k6 Fp. Zavaró hátrány.",
		"A hatás kívülről ártalmatlannak tűnik, valójában veszélyes belső sérüléssel jár.","Gyenge (belső) vérzés. Gyenge fájdalom.",
		"A belső szervek elszakdnak, felrepednek.","Mérsékelt (belső) vérzés. Mérsékelt fájdalom. Jelentős hátrány*.",
		null),
(8,"8","Has baloldalt",
		"A csapás kellemetlen hastájéli zúzódással jár, de komoly sérülész nem okoz.","+k6 Fp.",
		"Fájdalmas, a mozgást nehezítő zúzódás a törzs izmaiban.","+k6 Fp. Zavaró hátrány.",
		"A hatás kívülről ártalmatlannak tűnik, valójában veszélyes belső sérüléssel jár.","Gyenge (belső) vérzés. Gyenge fájdalom.",
		"A belső szervek elszakdnak, felrepednek.","Mérsékelt (belső) vérzés. Mérsékelt fájdalom. Jelentős hátrány*.",
		null),
(9,"9","Ágyék",
		"Öv alatti ütés! Nem különnösen érzékeny ponton.",null,
		"A csapás érzékeny pontot ér, de a hatás szerncsére nem maradandó.","+k10 Fp. 3 körre Jelentős hátrány.",
		"Az oldalról lesújtó csapás megrepeszti a csípőcsontot.","Gyenge vérzés. Gyenge fájdalom. Jelentős hátrány. Haladási sebesség: 60%.",
		"A széthasad csípőcsont belső sérülést okoz.","Gyenge (belső) vérzés. Heves fájdalom. Végzetes hátrány. Haladási sebesség: 20%",
		null);


		
CREATE TABLE bruise_back (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	damage_lethal varchar(200),
	affect_lethal varchar (200),
	commenting varchar(100)
);			


INSERT INTO bruise_back (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, damage_lethal, affect_lethal, commenting) VALUES
(1,"0","Jobb lapocka",
		"A csapás fájdamas zúzódást okoz a lapocka környékén vagy a csukjás izomban.",null,
		"A zúzás megrepeszti a lapockát, de ezzel el is veszíto erejét.","Gyenge fájdalom.",
		"A fegyver eltöri a lapockacsontot és leszakítja az itt tapadó hátizmokat egy részét.","Gyenge vérzés. Mérsékelt fájdalom. Jobb kar Részleges bénulása.",
		"A csapás eltöri és kimozdítja helyéről a lapockát.","Mérsékelt vérzés. Mérsékelt fájdalom. Jobb kar Teljes bénulása.",
		null),
(2,"1-2","Bal lapocka",
		"A csapás fájdamas zúzódást okoz a lapocka környékén vagy a csukjás izomban.",null,
		"A zúzás megrepeszti a lapockát, de ezzel el is veszíto erejét.","Gyenge fájdalom.",
		"A fegyver eltöri a lapockacsontot és leszakítja az itt tapadó hátizmokat egy részét.","Gyenge vérzés. Mérsékelt fájdalom. Bal kar Részleges bénulása.",
		"A csapás eltöri és kimozdítja helyéről a lapockát.","Mérsékelt vérzés. Mérsékelt fájdalom. Bal kar Teljes bénulása.",
		null),
(3,"3","Jobb hát",
		"A csapás lilára, duzzadtra zúzza a hátizmot, de nem jár végzetes sérüléssel.","+k6 Fp.",
		"A csapás erejét felfogják a megrepedő bordák, így nem okoz belső sérülést.","Gyenge fájdalom. +k6 Fp.",
		"A csapás összetör több bordát, csontszilánkok felsértik a tüdőt.","Gyenge (belső) vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A szétzúzott bordák átjárják a tudőt. Kívülről csak véraláfutás és duzzanat látható.","Mérsékelt (belső) vérzés. Heves fájdalom. Jelentős hátrány.",
		null),
(4,"4","Bal hát",
		"A csapás lilára, duzzadtra zúzza a hátizmot, de nem jár végzetes sérüléssel.","+k6 Fp.",
		"A csapás erejét felfogják a megrepedő bordák, így nem okoz belső sérülést.","Gyenge fájdalom. +k6 Fp.",
		"A csapás összetör több bordát, csontszilánkok felsértik a tüdőt.","Gyenge (belső) vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A szétzúzott bordák átjárják a tudőt. Kívülről csak véraláfutás és duzzanat látható.","Mérsékelt (belső) vérzés. Heves fájdalom. Jelentős hátrány.",
		null),
(5,"5","Jobb derék",
		"Fájdalmas, duzzadt zúzódás a csípőcsont táján.","+k6 FP.",
		"A megrepedő csípőcsont elnyeli a csapás erejét.","Gyenge fájdalom.",
		"A csapás lágy részen éri a törzset, súlyos belső sérülést okozva.","Gyenge (belső) vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A csúf látványt nyújtó sérülés halálos: belső szervek leszakadnak és felrepednek.","Mérsékelt (belső) vérzés. Mérsékelt fájdalom. Jelentős hátrány.",
		null),
(6,"6","Bal derék",
		"Fájdalmas, duzzadt zúzódás a csípőcsont táján.","+k6 FP.",
		"A megrepedő csípőcsont elnyeli a csapás erejét.","Gyenge fájdalom.",
		"A csapás lágy részen éri a törzset, súlyos belső sérülést okozva.","Gyenge (belső) vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A csúf látványt nyújtó sérülés halálos: belső szervek leszakadnak és felrepednek.","Mérsékelt (belső) vérzés. Mérsékelt fájdalom. Jelentős hátrány.",
		null),
(7,"7","Ülep",
		"Az izmok elnyelik a csapás erejét, habár a tűz melletti üldögélés ideig-óráig kevésbé kellemes.",null,
		"A szerencsétlenül érkező csapás eltalálja és megrepeszti a farokcsontot.","Haladási sebesség: 80%. Mérsékelt fájdalom.",
		"A csapás erejét az izmok sem fogják fel, így eltöri a combnyakat.","Haladási sebesség: 30%. Jelentős hátrány. Mérsékelt fájdalom.",
		"A comnyak nyílt törése az elmozduló csontok átfúrják az izmokat és a bőrt.","Mérsékelt vérzés. Jelentős háztány. Az adott láb Teljes bénulása.",
		null),
(8,"8-9","Gering",
		"Nyilalló fájdalom a gerinctájon. Az itt futó izmok felfogják a csapást.","+k6 Fp.",
		"A csapás a gerinc környéki izmokat roncsolja. Minden derékból, törzsból végzett mozgás erős fájdalommal jár.","Mérsékelt fájdalom. Zavaró hátrány.",
		"A megrepedő, elmozduló csigolyák felfogják az ütést, de nyomják a gerincvelőt.","Mérsékelt fájdalom. Részleges bénulás mindkét lábon.",
		"Gerinctörés. Habár a gerinc összeforrhat, a bénulás csak mágiával gyógyítható.","Ájulás. Törzs és lábak Teljes bénulása.",
		null);



			
CREATE TABLE bruise_arm (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	commenting varchar(100)
);				
		

INSERT INTO bruise_arm (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, commenting ) VALUES
		
(1,"0-3","Váll",
		"Az ütés a vállizmot éri és zsibbasztja."," Zavaró hátrány.",
		"A csapás roncsolja a vállízületet. A szalagok szakadnak, a csontok repednek.","A kar Részleges bénulása. Gyenge fájdalom.",
		"A csapás tönkrezúzza a vállízületet. Gyenge vérzés.","A kar Teljes bénulása. Mérsékelt fájdalom.",
		null),
(2,"3-4","Felkar",
		"Az ütés a karizmot találja el, zsibbasztó fájdalmat okozva.","Zavaró hátrány.",
		"A csapás következtében elreped a felkarcsont.","Mérsékelt fájdalom. Könyöktől levelé Részleges bénulása.",
		"A csapás kettétöri a felkarcsontot. Gyenge vérzés.","Mérsékelt fájdalom. Könyöktöl lefelé teljes bénulás.",
		null),
(3,"5","Könyök",
		"Fájdalmas porcleválást okozó ütés éri a könyököt.","Zavaró hátrány. Gyenge fájdalom.",
		"A cspás eltöri a sérülékeny könyökízület csontjait.","Alkar Teljes bénulása. Mérsékelt fájdalom.",
		"A csapás nyílt törést okoz a könyökízületnél, a csontvégek felszaggatják az idegeket.","Mérsékelt vérzés. Alkar Teljes bénulása. Heves fájdalom.",
		null),
(4,"6-7","Alkar",
		"Az ütés megrepeszti az egyik alkarcsontot.","+k6 Fp.",
		"Csukló Részleges bénulása. Az erős ütés következtében eltörik az egyik alkarcsont.","Csukló Részleges bénulása. Gyenge fájdalom.",
		"A zúzó erejú ütés eltöri mindkét alarcsontot.","Csukló Teljes bénulása. Mérsékelt fájdalom.",
		null),
(5,"8","Csukló",
		"Az ütés porcleválást okoz a csuklóízületben. A sérült kejti kezéből a fegyverét.","Zavaró hátrány.",
		"Az ütés hatásaként a csuklóízületben több csont eltörik.","Kézfej, ujjak Részleges bénulása. Gyenge fájdalom.",
		"Az ütés használhatatlanná roncsolja a csuklóízület érzékeny csontjait.","Kézfej, ujjak Teljes bénulása. Gyenge vérzés. Mérsékelt fájdalom.",
		null),
(6,"9","Kézfej",
		"Az ütés hatására egy ujj eltörik.","A kézre Zavaró hátrány. Gyenge fájdalom.",
		"A csapás több ijjat is eltör, fegyvert forgatni, súlyt emelni az adott kézzel lehetetlen.","Az ujjak Részleges bénulása. Gyenge fájdalom.",
		"A lesíjtó fegyver szétmorzsolja a kézhát finom csontjait.","A kézfej Teljes bénulása. Mérsékelt fájdalom.",
		null);	
		
		
		
CREATE TABLE bruise_leg (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	commenting varchar(100)
);			
			
	
INSERT INTO bruise_leg (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, commenting) VALUES
		
(1,"0-4", "Comb",
		"Az ütés kirobbanó, szibbasztó fájdalmat és véraláfutást eredményez a combizomban.","Zavaró hátrány.",
		"A lesújtó fegyver megrepeszti a combcsontot.","Láb Részleges bénulása. Haladási sebesség: 70%.",
		"Az elöprő erejű ütés eltöri az combokba izmokba ágyazott combcsontot.","Láb Teljes bénulása. Mérsékelt fájdalom. Haladási sebesség: 30%.",
		null),
(2,"5","Térd",
		"Az ütés porcleválást okoz a térdízületben, miáltal minden lépés erős fájdalommal jár.","Haladási sebesség: 80%. +k10 Fp. Zavaró hátrány.",
		"A lecsapó fegyver megzúzza a térdízületet, szítszaggatja az inszallagokat.","Haladási sebesség: 50%. Zavaró hátrány. Mérsékelt fájdalom.",
		"A csapás kövezkeztében torrzá roncsolódik a teljes térdízület.","Térd Teljes bénulása. Mérsékelt fájdalom. Gyenge vérzés. Haladási sebesség: 20%.",
		null),
(3,"6-7", "Lábszár",
		"Fájdalmas ütés a sípcsonton.","+k10 Fp.",
		"Az ütés megrepeszti a sípcsontot."," Gyenge fájdalom. Zavaró hátrány. Haladási sebesség: 80%.",
		"A lábat elkaszáló fegyver kettétöri a sípcsontot."," Jelentős hátrány. Mérsékelt fájdalom. Haladási sebesség: 40%",
		null),
(4,"8","Boka",
		"Az ütés hatására bevérzik a bokaízület.","Haladási sebesség: 70%. Gyenge fájdalom. Zavaró hátrány.",
		"A csapás eltöri a bokaízület egyik csontját, miáltal a lábfej bizonyos irányokban nem mozdítható.","Haladási sebesség: 50%. Mérsékelt fájdalom. Zavaró hátrány.", 
		"A fegyver szétzúzza a bokaízületet. A csontok eltörnek, a porcok leválnak, szalagok elszakadnak.","Lábfej Teljes bénulása. Mésékelt fájdalom. Zavaró hátrány. Haladási sebesség: 30%.",
		null),
(5,"9","Lábfej",
		"A felülről lesújtó csapás két lábujjat is szétzúz.","Gyenge fájdalom. Haladási sebesség 90%.",
		"A lábhát több csontja eltörik a lesújtó fegyver csapása alatt.","Haladási sebesség: 70%. Gyenge fájdalom. Zavaró hátrány.",
		"Az elemi erővel alázúduló csapás szilánkokra morzsolja a lábfejet.","Mérsékelt fájdalom. Lábfej Teljes bénulása. Haladási sebesség: 30%.",
		null);


		

		

		
CREATE TABLE shear_damages_group(
	tableName varchar(20) PRIMARY KEY,
	area_group varhcar(20),
	sp_damage_mild varchar(20),
	sp_damage_serious varchar(20),
	sp_damage_dangerous varchar(20),
	sp_damage_lethal varchar(20),
	commenting varchar(100)
);

INSERT INTO shear_damages_group (tableName, area_group, sp_damage_mild, sp_damage_serious, sp_damage_dangerous, sp_damage_lethal, commenting) VALUES
("shear_head", "Fej", "1-2 Ép", "3-4 Ép", "5-6 Ép", "7+ Ép", null),
("shear_front", "Törzs előlről", "1-2 Ép", "3-6 Ép", "7-9 Ép", "10+ Ép", "* lásd még ET Betegségek leírás; tüdősérülés az Állóképességet felezi"),
("shear_back", "Törzs hátulról", "1-2 Ép", "3-6 Ép", "7-9 Ép", "10+ Ép", null),
("shear_arm", "Kar", "1-2 Ép", "3-4 Ép", "5-6 Ép", null, "MAx 6 Ép sebzése lehet"),
("shear_leg", "Láb", "1-2 Ép", "3-4 Ép", "5-6 Ép", null, "Max 8 Ép sebzése lehet");		
		
		
CREATE TABLE shear_head (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	damage_lethal varchar(200),
	affect_lethal varchar (200),
	commenting varchar(100)
);


INSERT INTO shear_head (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, damage_lethal, affect_lethal, commenting) VALUES
		
(1,"0-2","Agykoponya",
		"A fegyver mély vágást ejt a fejtetőn, de nem szakítja be a koponyát.", "+k6 Fp.",
		"Gyenge vérézs. A vágás bezúzza a koponyát, de ezzel el is veszíti erejét, nem éri el az agyat.","Zavaró hátrány. Mérsékelt fájdalom. Gyenge vérzés.",
		"A penge hosszan felnyitja a koponyát.","Végzetes hátrány. Mérsékelt fájdalom. Mérsékelt vérzés.",
		"A vágás átszakítja a koponyát és végzetes agysérülést okoz.","Mérsékelt vérzés. Ájulás,",
		null),
(2,"3-4","Homlok",
		"Csontig hatoló, hosszú vágás a homlokon, a vér a szembe csorog.","+k6 Fp. Gyenge vérzés. Zavaró hátány.",
		"A vágás nem csak a bőrt sérti fel, de megrepeszti a homlokcsontot is.","Zavaró hátrány. Gyenge vérzés.",
		"A penge a fejtetőtől at orrig futó vágást ejt, beszakítva a koponyacsontot.","Jelentős hátrány. Gyenge fájdalom. Mérsékelt vérzés.",
		"A vágás fejtetőtől a homlokig felnyitja a koponyát.","Mérsékelt vérzés. ájukás",
		null),
(3,"5","Halánték",
		"A vágás a legszélén éri a kemény homlokcsontot. Csúf, de ártalmatlan seb.","+k6 Fp.",
		"A vágás fultől a haléntékig fut, de nem szakítja be a koponyát.","+k6 Fp. Gyenge vérzés. Zavaró hátrány.",
		"A penge átszakítja a hakántékot, elvágja az itt futó ereket.","Heves vérzés. Jelentős hátrány. Mérsékelt fájdalom.",
		"A vágás nyomán beszakas a halánték és az oldalsó koponya.","Heves vérzés. Ájulás.",
		null),
(4, "6-7","Arckoponya",
		"A vágás nyomán mély, csúf seb nyílik az arcon. A szemek, az orr nem sérül.","+k6 Fp.",
		"A penge megséri a szemet, de nem séri meg a ményebben lapuló szemgolyót. Kicsorduló vér szavarja a látást.","Gyenge vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A mély vágás kereszben fut az arcon, megzúzza a járomcsontot, átvágja az orrot vagy az ajkakat.","Mérsékelt vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A vágás szinte leszakítja az állkapcsot, lebénítja a fél arcot, de elkerül a szemet.","Mérsékelt vérzés. Heves fájdalom. Jelentős hátrány.",
		null),
(5, "8-9", "Nyak/Tarkó",
		"A penge belevág a nyakba, végzetesnek tűnő, mégsem komoly sebet ejtve.","+k6 Fp. Gyenge vérzés.",
		"A vágás feltépi a nyakat és többet, az ott futó erek, szalagok közül.","Mérsékelt vérzés. Gyenge fájdalom. Zavaró hátrány.",
		"A vágás mélyen a nyakba hatol, átmetszve a nyaki verőeret.","Heves vérzés. Végzetes hátrány. Mérsékelt fájdalom.",
		"A nyak Részleges bénulása. A penge kis híján átvágja a nyakat. Feltéi az ereket és a csigolyákban akad el.","Heves vérzés. Teljes bénulás. Mérsékelt fájdalom.",
		null);		


	
CREATE TABLE shear_front (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	damage_lethal varchar(200),
	affect_lethal varchar (200),
	commenting varchar(100)
);		

INSERT INTO shear_front (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, damage_lethal, affect_lethal, commenting) VALUES
(1,"0","Jobb kulcscsont", 
		"A vágá a jobb kulcscsont felett az izmokba hatol.","+k6 Fp.",
		"A felülről érkező vágás a kulcscsontig hatol, mély, kellemetlen sebet ejtve a nyak alatt.","Mérsékelt vérzés. Zavaró hátrány.",
		"A vágás felülről csap le a vállra, szétronycsolja az ízmokat és megrepeszti a kulcscsontot.","Mérsékelt vérzés. Jobb kar Részleges bénulása.",
		"A lezúduló penge átvágja a vállat és a kulcscsontot. Kis híján a szívig hatol.","Heves vérzés. Jelentős hátrány. Jobb kar Teljes bénulása.",
		null),
(2,"1","Bal kulcscsont",
		"A vágá a bal kulcscsont felett az izmokba hatol.","+k6 Fp.",
		"A felülről érkező vágás a kulcscsontig hatol, mély, kellemetlen sebet ejtve a nyak alatt.","Mérsékelt vérzés. Zavaró hátrány.",
		"A vágás felülről csap le a vállra, szétronycsolja az ízmokat és megrepeszti a kulcscsontot.","Mérsékelt vérzés. Bal kar Részleges bénulása.",
		"A lezúduló penge átvágja a vállat és a kulcscsontot, majd a tüdőbe hatol. Heves vérzés.","Jelentős hátrány. Bal kar Teljes bénulása.",
		null),
(3,"2","Szegycsont",
		"Csak a penge hegye éri el a törzset, átmetszi a mellizom bőt alatti rostjait és felkarcolja a szegycsontot.","+k6 Fp.",
		"Hosszú, nem végzetesen mély vágás, mely a nyaktól egészen a köldökig fut.","Zavaró hátrány. Gyenge fájdalom. Gyenge vérzés.",
		"A vágás a mellizomnál hatol a testbe, leszakítja a szegycsontot, de elkerüli a szivet.","Mérsékelt vérzés. Jelentős hátrány. Mérsékelt fájdalom.",
		"A vágás keresztben felnyitja a mellkast, a tüdőbe hatol és felsérti a szívkörnyéki nagyereket.","Végzetes hátrány. Heves vérzés. Heves fájdalom.",
		null),
(4,"3","Bal mellkas",
		"A vágás eltérül és lecsupaszítja a bal oldali bordákat. A seb veszedelmesnek látszik, holott ártalmatlan.","+k6 Fp.",
		"Az oldalról érkező vágás elakad a megroppanó és elmozduló bordákban.","Zavaró hátrány. Gyenge fájdalom.",
		"A penge oldalt felnyitja a törzset, keresztül hatolva a kettétörő bordákon.","Zavaró hátrány. Mérsékelt vérzés. Mérsékelt fájdalom.",
		"A penge áttöri a bordákat és feltépi a szívkörnyéki nagyereket, esetleg magát a szivet is.","Jelentős hátrány. Heves vérzés. Mérsékelt fájdalom.",
		null),
(5,"4","Jobb mellkas",
		"A vágás eltérül és lecsupaszítja a bal oldali bordákat.","+k6 Fp.",
		"Az oldalról érkező vágás elakad a megroppanó és elmozduló bordákban.","Zavaró hátrány. Gyenge fájdalom.",
		"A penge oldalt felnyitja a törzset, keresztül hatolva a kettétörő bordákon.","Zavaró hátrány. Mérsékelt vérzés. Mérsékelt fájdalom.",
		"A penge áttöri a bordákat és a tüdőbe hatol.","Végzetes hátrány. Mérsékelt vérzés. Mérsékelt fájdalom.",
		null),
(6,"5-6","Gyomorszáj",
		"A penge hegye épphogy eléri a törzset. Átmetszi a hasizom felső rostjait.","Gyenge fájdalom. Zavaró hátrány.",
		"A csapás felülről levelé átvágja a hasizmot, de nem sérti fel a belső szerveket.","Zavaró hátrány. Gyenge vérzés. Gyenge fájdalom.",
		"A szemből érkező vágás a szegycsont alatt felnyitja a törzset, feltárva a belső szerveket.","Jelentős hátrány. Mérsékelt vérzés. Mérsékelt fájdalom.",
		"A vágás szegycsonttól ágyékig hatol. Erre mondják, hogy kiontotta ellenfele beleit. Heves vérzés.","Jelentős hátrány. Heves fájdalom.",
		null),
(7,"7","Has jobb oldalt",
		"A penge a bordák alatt belevág a lágy hasfalba, legfeljebb izmokat sért fel.","+k6 Fp.",
		"A csapás áthatol az oldalsó törzsizmokon, de nem éri el a belső szerveket.","+k6 Fp. Gyenge vérzés. Zavaró hátrány.",
		"A vágás jobb oldalról érkezik és mélyen a törzsbe, a belső szervekbe hatol.","Mérsékelt vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A vágás oldalt nyitja fel a hasat, hosszan és mélyen fut, a belső szerveket is szétroncsolja.","Heves fájdalom. Mérsékelt vérzés. Jelentős hátrány.",
		null),
(8,"8","Has bal oldalt",
		"A penge a bordák alatt belevág a lágy hasfalba, legfeljebb izmokat sért fel.","+k6 Fp.",
		"A csapás áthatol az oldalsó törzsizmokon, de nem éri el a belső szerveket.","+k6 Fp. Gyenge vérzés. Zavaró hátrány.",
		"A vágás bal oldalról érkezik és mélyen a törzsbe, a belső szervekbe hatol.","Mérsékelt vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A vágás oldalt nyitja fel a hasat, hosszan és mélyen fut, a belső szerveket is szétroncsolja.","Heves fájdalom. Mérsékelt vérzés. Jelentős hátrány.",
		null),
(9,"9","Ágyék",
		"A has alján keresztben ejtett vágás fájdalmas, de nem nyitja fel a hasfalat.","+k10 Fp.",
		"Az oldalról lesújtó vágás a megzúzódó csípőcsontban akad el.","Gyenge vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A keresztben elhúzott penge hosszú sebet ejt, felnyitja a hasat, de nem roncsolja a belső szerveket.","Mérsékelt vérzés. Zavaró hátrány, Mérsékelt fájdalom.",
		"A vágás szétroncsolja a csípőt, feltépi a verőereket és a belső szerveket.","Heves vérzés. Végzetes hátrány. Heves fájdalom.",
		null);



CREATE TABLE shear_back (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	damage_lethal varchar(200),
	affect_lethal varchar (200),
	commenting varchar(100)
);		
		
		
INSERT INTO shear_back (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, damage_lethal, affect_lethal, commenting) VALUES
(1,"0-1","Jobb lapocka",
		"A vágást vértként felfogja a kemény lapockacsont, így csak izmokat károsít.",null,
		"A felülről lesújtó csapás a vállba hasít, izomrostokat vág át.","Gyenge fájdalom. Zavaró hátrány.",
		"A vállra lecsapó penge megzúzza a lapockát, átvágja az itt tapadó vállizmokat.","Mérsékelt vérzés. Jobb kar Részleges bénulása. Mérsékelt vérzés.",
		"A vágás felülről hatol a törzsbe, elmozdítja a lapockát ls eléri a tüdőt.","Mérsékelt vérzés. Végzetes hátrány. Mérsékelt fájdalom.", 
		null),
(2,"2","Bal lapocka",
		"A vágást vértként felfogja a kemény lapockacsont, így csak izmokat károsít.",null,
		"A felülről lesújtó csapás a vállba hasít, izomrostokat vág át.","Gyenge fájdalom. Zavaró hátrány.",
		"A vállra lecsapó penge megzúzza a lapockát, átvágja az itt tapadó vállizmokat.","Mérsékelt vérzés. Bal kar Részleges bénulása. Mérsékelt vérzés.",
		"A vágás felülről hatol a törzsbe, elmozdítja a lapockát ls eléri a tüdőt.","Mérsékelt vérzés. Végzetes hátrány. Mérsékelt fájdalom.",
		null),
(3,"3","Jobb hát",
		"A vágás nyomán hosszú seb nyílik a háton, a penge nem hatol át a bordaíven.","Gyenge vérzés.",
		"A csapás a megrepedő bordákon veszíti el erejét, nem jut a tüdőig.","Gyenge vérzés. Gyenge fájdalom. Zavaró hátrány.",
		"A penge átvágja a széles hátizmot, eltör több bordát is.","Mérsékelt fájdalom. Mérsékelt vérzés. A jobb kar Részleges bénulása.",
		"A penge áthatol a hátizmon és a bordaíven, mélyen a tüdőben állapodik meg.","Mérsékelt vérzés. Jelentős hátrány. Mérsékelt fájdalom.",
		null),
(4,"4","Bal hát",
		"A vágás nyomán hosszú seb nyílik a háton, a penge nem hatol át a bordaíven.","Gyenge vérzés.",
		"A csapás a megrepedő bordákon veszíti el erejét, nem jut a szívig.","Gyenge vérzés. Gyenge fájdalom. Zavaró hátrány.",
		"A penge átvágja a széles hátizmot, eltör több bordát is, de mélyebbre nem jut.","Mérsékelt fájdalom. Mérsékelt vérzés.",
		"A bal kar Részleges bénulása. A penge áthatol a hátizmon és a bordaíven, mélyen a szívben állapodik meg.","Heves vérzés. Jelentős hátrány. Mérsékelt fájdalom.",
		null),
(5,"5","Jobb derék",
		"A penge a bordaív alatt belevág a derékba, felsérve az oldalsó törzsizmokat.","+k6 Fp. Zavaró hátrány.",
		"A csapás áthatol a deréktáju törzsizmokon, de nem éri el a belső szerveket.","Gyenge vérzés. Zavaró hátrány.",
		"A vágás jobboldalról érkezik és mélyen a törzsbe hatol.","Mérsékelt vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A vágás oldalról, mélyen a törzsbe szalad, több belső szervet is szétroncsolva.","Mérsékelt fájdalom. Mérsékelt vérzés. Jelentős hátrány.",
		null),
(6,"6","Bal derék",
		"A penge a bordaív alatt belevág a derékba, felsérve az oldalsó törzsizmokat.","+k6 Fp. Zavaró hátrány.",
		"A csapás áthatol a deréktáju törzsizmokon, de nem éri el a belső szerveket.","Gyenge vérzés. Zavaró hátrány.",
		"A vágás baloldalról érkezik és mélyen a törzsbe hatol.","Mérsékelt vérzés. Mérsékelt fájdalom. Zavaró hátrány.",
		"A vágás oldalról, mélyen a törzsbe szalad, több belső szervet is szétroncsolva.","Mérsékelt fájdalom. Mérsékelt vérzés. Jelentős hátrány.",
		null),
(7,"7","Ülep",
		"A vágás kihasít egy darabot az izmos hátsófélből. A seb igazán csak a békés üldögélést zavarja.",null,
		"A penge átlósan belevág a farizomba, minden mozdulatra fájdalmasan nyilalló sebet okozva.","Gyenge vérzés. Haladási sebesség: 50%.",
		"A vágás mélyen a farizomba, egészen a medencecsontig hatol.","Mérsékelt vérzés. Zavaró hátrány. Gyenge fájdalom. Haladási sebesség: 30%.",
		"A csapás átvágja a farizmot, roncsolja a combnyakat, feltép a combba futó verőeret.","Heves vérzés. Jelentős hátrány. Haladási sebesség: 10%.",
		null),
(8,"8-9","Gerinc",
		"A vágás kereszben végigmetszi a hátat, de a gerincet nem képes átvágni.","+k6 Fp.",
		"A vágás átmetszi a középső hátizmokat, csak a gerinccsigolyákban akad el.","Mérsékelt vérzés. Gyenge fájdalom. Zavaró hátrány.",
		"Hideg acél hatol a csigolyák közé, de nem sérti meg a gerincvelőt. Mérsékelt vérzés.","Jelentős hátrány. Mérsékelt fájdalom. k6 órára Részleges bénulás.",
		"Az elemi erejű csapás átvágja a gerincet, s vele a verőereket és a gerincvelőt.","Heves vérzés. Teljes bénulás. Heves fájdalom.",
		null);
	

	
CREATE TABLE shear_arm (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	commenting varchar(100)
);		
		
INSERT INTO shear_arm (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, commenting ) VALUES
	
(1,"0-2", "Váll",
		"A vágás a vállizmokat éri el és felsérti a bőrt, felső izomrostokat.","Zavaró hátrány. Gyenge vérzés.",
		"A vágás roncsolja a vállízületet. A szalagokat metsz át, a csontokat is sért.","A kar Részleges bénulása. Mérsékelt vérzés. Gyenge fájdalom.",
		"A penge átjárja a vállízületet, megsérit a karba tartó verőeret.","Heves vérzés. A kar Teljes bénulása. Mérsékelt fájdalom.",
		null),
(2,"3-4", "Felkar",
		"Az vágás a karizmokat találja el, felszíni sérülést eredményez.","Zavaró hátrány. Gyenge vérzés.",
		"A vágás mélyebbre hatolva, mélyen belemar a felkar egyes izmaiba, nagyobb ereit.","Mérsékelt vérzés. Mérsékelt fájdalom.",
		"Könyöktől lefelé Részleges bénulás. A vágás mély, a csontig hatóló. Felkari izmokat vág át és ereket sért meg.","Mérsékelt fájdalom. Mérsékelt vérzés. Könyöktől lefelé Teljes bénulás.",
		null),
(3,"5","Könyök",
		"A vágás felszántja a könyökízüetet, de inkább a felszínben tesz kárt, porcok, szalagok sérülése enyhe.","Zavaró hátrány. Gyenge fájdalom.",
		"A vágás belemetsz a könyökízületbe, megsértve porcokat, szalagokat, ereket.","Zavaró hátrány. Gyenge vérzés. Könyöktől lefelé Részleges bénulás.",
		"A penge mélyen belevág a könyökízületbe, használhatatlanná téve azt.","Mérsékelt vérzés. Mérsékelt fájdalom. Könyöktől lefelé a kar Teljes bénulása.",
		"Max 5 Ép sebzése lehet"),
(4,"6-7","Alkar",
		"A vágás az alkart a külső élénél felmetszi, inkább bőrt és csonthártyát sért.","+k6 Fp.",
		"A vágás mélyebbre hatol az alkarban, inakat, izmokat sért meg, a singcsont állítja meg.","Mérsékelt fájdalom. Zavaró hátrány. Gyenge vérzés. A csukló, kézfej, ujjak Részleges bénulása.",
		"A vágás ereje akkora, hogy átvágja a sincsontot, belemélyed az orsócsontba is. Az izmok és inak károsodása komoly.","Jelenős hátrány. Mérsékelt fájdalom. Mérsékelt vérzés. A csukló, kézfej és ujjak Teljes bénulása.",
		"Max 4 Ép sebzése lehet"),
(5,"8","Csukló",
		"A vágás felmetszi a csuklót, de inkább a bőr sérült meg.","Zavaró hátrány. Gyenge vérzés. +k6 Fp.",
		"A penge mélyebben hatol a csuklóba, inakat, nagyobb vénákat sért.","Mérsékelt vérzés. Gyenge fájdalom. Csukló és kézfej Részleges bénulása.",
		"A vágás mélyen belehasít a csuklóba, csaknem átmetszi azt.","Jelenős hátrány. Mérsékelt fájdalom. Mérsékelt vérzés. Csukló és kézfej Teljse bénulása.",
		null),
(6,"9","Kézfej",
		"A vágás a kézfejet éri, egy-egy ujjat átmetsz.","+k10 Fp. Zavaró hátrány. Gyenge fájdalom. Gyenge vérzés.",
		"A penge a kézhátat éri, belevág a kéztőcsontokba, egyes ujjfeszítő-inakat is átvág.","A kéz Részleges bénulása. Gyenge vérzés. Mérsékelt fájdalom.",
		"A vágás mélyen belemar a kézfejbe, szétroncsolja. A kézben tartott fegyver a földre esik.","Mérsékelt fájdalom. Mérsékelt vérzés. A kézfej Teljes bénulása.",
		null);

		
CREATE TABLE shear_leg (
	id integer(2) PRIMARY KEY,
	dice varchar(5),
	area varchar(15),
	damage_mild varchar(200),
	affect_mild varchar (200),
	damage_serious varchar(200),
	affect_serious varchar (200),
	damage_dangerous varchar(200),
	affect_dangerous varchar (200),
	commenting varchar(100)
);	
		
INSERT INTO shear_leg (id, dice, area,
		damage_mild, affect_mild, damage_serious, affect_serious, damage_dangerous, affect_dangerous, commenting ) VALUES
		
(1,"0-4","Comb",
		"A penge a comizomba mar, hosszú, de ártalmatlan vágást ejtve.","Gyenge vérzés.",
		"Csontig hatoló, kellemetlen vágás, mely minden lépésre sajgó fájdalmalommal válaszol.","Mérsékelt vérzés. Zavaró hátrány. Haladási sebesség: 70%.",
		"A vágás oldalról érketik, zúzással is felér. Átvágja a combot, még a csontot is megrepeszti.","A láb Részleges bénulása. Zavaró hátrány. Haladási sebesség 50%.",
		null),
(2,"5","Térd",
		"A vágás hosszában metsz a térdkalácsba, így nem vát át inakat, csak a csonot zúzza meg.","+k10 Fp, Haladási sebesség 80%.",
		"Az oldalról lecsapó fegyver belevág a térdízületbe, de ezzel el is feszíti erejét.","Zavaró hátrány. Gyenge fájdalom. Haladási sebesség: 50%.",
		"A csapás szinte térdben levágja a lábat, tönkrezőzza a térdízületet, elmetszi az ereket és inakat.","Lábszártól lefelé Teljes bénulás. Mérsékelt fájdalom. Mérsékelt vérzés. Haladási sebesség: 20%.",
		null),
(3,"6-7","Lábszár",
		"A vágás a vádliba mar, de csak fájdalmas sebet ekt.","+k6 Fp.",
		"A hideg acél a sípcsontok hatol, izzó fájdalmat lobbantva a lábban.","+k6 Fp. Gyenge vérzés.",
		"A vágás ereje a sípcsont nyílt törését eredményezi, kis híján átvágja a lábat.","Mérsékelt fájdalom. Mérsékelt vérzés. Lábszár Részleges bénulása. Haladási sebesség: 50%.",
		null),
(4,"8","Boka",
		"Csontot karcoló, kellemetlen, de ugyanakkor ártalmatlan vágás a boka egyik oldalán.","Gyenge vérzés. Haladási sebesség: 90%.",
		"A vágás szembpl éri a bokahajlatot, mély sebet ejt, szalagokat vág el, roncsolja az ízületet.","Gyenge vérzés. Lábfej Részleges bénulása. Haladási sebesség: 60%.",
		"A penge átvágja az Achilles-ínat, majdnem leszakítja a lábfejet.","Lábfej Teljes bénulása. Jelentős hátrány. Haladási sebesség: 30%.",
		null),
(5,"9","Lábfej",
		"A penge a lábfej-hátba mar, felsérti, megzúzza a keskeny csontokat.","Gyenge vérzés. Haladási sebesség: 80%.",
		"A csapás oldalról bevágja a lábfejet, több lábujjat is használhatatlanná tesz.","Gyenge vérzés. Lábfej Részleges bénulása. Gyenge fájdalom. Haladási sebesség: 70%.",
		"A vágás kereszben, felülről csap le a lábfejre. Átvágja a csontokat, kevés híján, leválasztja a lábfej elejét.","Mérsékelt fájdalom. Jelentős hátrány. Gyenge vérzés. Lábfej Részleges bénulása. Haladási sebesség: 40%.",
		null);
		
		

